### ISSUE TITLE
코드 리팩토링: 환경 설정 값 관리 개선

### ISSUE THREAD

**Issue by TaskerJang** [TaskerJang/dnd-12th-5-backend#9]
## 현재 상황
프로젝트에서는 환경 변수와 설정 값들이 개별 클래스나 서비스에서 `@Value` 어노테이션을 통해 직접 주입받아 사용하고 있습니다. 이러한 방식은 설정 값의 재사용성을 저하시키고, 설정 값의 변경 시 여러 클래스를 수정해야 하는 문제를 야기합니다.

특히, 아래와 같은 패턴이 여러 곳에서 발견됩니다:

```java
@Value("${kakao.client.id}")
private String clientId;

@Value("${kakao.client.secret}")
private String adminKey;

@Value("${kakao.redirect.uri}")
private String redirectUri;

// 다른 클래스에서도 동일한 설정 값 중복 주입
```

### 문제점
- 설정 값의 중복 주입
- 설정 값 변경 시 여러 클래스 수정 필요
- 설정 파일과 코드 간의 결합도 증가
- 테스트 환경에서 설정 값 모킹의 어려움
- 설정 값의 일관성 유지 어려움

### 1. 설정 클래스 구현
각 도메인 또는 외부 시스템별 설정을 위한 클래스를 구현하여 관련 설정을 그룹화합니다:

```java
@Getter
@ConfigurationProperties(prefix = "kakao")
@Component
public class KakaoProperties {
    private String clientId;
    private String clientSecret;
    private String redirectUri;
    
    // getter, setter 생략
}

@Getter
@ConfigurationProperties(prefix = "aws")
@Component
public class AwsProperties {
    private S3 s3;
    private Cloudfront cloudfront;
    
    @Getter
    @Setter
    public static class S3 {
        private String bucketName;
        private String region;
    }
    
    @Getter
    @Setter
    public static class Cloudfront {
        private String domain;
    }
}

@Getter
@ConfigurationProperties(prefix = "app")
@Component
public class ApplicationProperties {
    private String baseUrl;
    private String apiVersion;
    private Security security;
    
    @Getter
    @Setter
    public static class Security {
        private long accessTokenExpirationTime;
        private long refreshTokenExpirationTime;
        private String tokenSecret;
    }
}
```

### 2. 설정 클래스 사용 예시
```java
@Service
@RequiredArgsConstructor
public class UserService {
    private final KakaoProperties kakaoProperties;
    private final RestTemplate restTemplate;
    
    public String getKakaoAccessToken(String code) {
        // 설정 클래스에서 값 참조
        String clientId = kakaoProperties.getClientId();
        String redirectUri = kakaoProperties.getRedirectUri();
        
        // 이하 생략
    }
}

@Service
@RequiredArgsConstructor
public class S3Service {
    private final AwsProperties awsProperties;
    
    private String getFileUrl(String filePath) {
        return String.format("https://%s/%s", 
                awsProperties.getCloudfront().getDomain(), 
                filePath);
    }
}
```

### 3. 통합 설정 관리를 위한 `application.yml` 구조화
```yaml
kakao:
  client-id: your-client-id
  client-secret: your-client-secret
  redirect-uri: your-redirect-uri

aws:
  s3:
    bucket-name: your-bucket-name
    region: ap-northeast-2
  cloudfront:
    domain: your-cloudfront-domain

app:
  base-url: https://api.picktory.net
  api-version: v1
  security:
    access-token-expiration-time: 3600000
    refresh-token-expiration-time: 2592000000
    token-secret: your-token-secret
```

### 4. 설정 활성화
`@EnableConfigurationProperties` 활성화:

```java
@SpringBootApplication
@EnableConfigurationProperties({
    KakaoProperties.class,
    AwsProperties.class,
    ApplicationProperties.class
})
public class PicktoryApplication {
    public static void main(String[] args) {
        SpringApplication.run(PicktoryApplication.class, args);
    }
}
```

## 기대효과
1. 설정 값의 중앙 집중화로 관리 용이성 증가
2. 설정 변경 시 하나의 클래스만 수정하면 됨
3. 타입 안전성 확보 (String이 아닌 강타입 사용)
4. 관련 설정값 그룹화로 가독성 향상
5. 테스트 용이성 증가 (설정 클래스 모킹)
6. 설정 값의 재사용성 증가
7. 설정 값 간의 관계 명시적 표현
8. 설정 검증 로직 추가 용이
